### ISSUE TITLE
Sample Code Running Error

### ISSUE THREAD

**Issue by aviralsangal** [microsoft/msrflute#14]
Hi,

I recently installed FLUTE and was trying the sample example given this repo's description. 

Following is the command which I ran:

python -m torch.distributed.run --nproc_per_node=3 e2e_trainer.py -dataPath ./testing/mockup -outputPath scratch  -config testing/configs/hello_world_local.yaml -task nlg_gru -backend nccl

Now, Following is the error which I received.

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
The data can be found here:  ./testing/mockup
Traceback (most recent call last):
  File "/home/linuxsys/Downloads/msrflute/e2e_trainer.py", line 226, in <module>
    shutil.copyfile(args.config, cfg_out)
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'testing/configs/hello_world_local.yaml'
The data can be found here:  ./testing/mockup
Traceback (most recent call last):
  File "/home/linuxsys/Downloads/msrflute/e2e_trainer.py", line 226, in <module>
    shutil.copyfile(args.config, cfg_out)
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'testing/configs/hello_world_local.yaml'
The data can be found here:  ./testing/mockup
Traceback (most recent call last):
  File "/home/linuxsys/Downloads/msrflute/e2e_trainer.py", line 226, in <module>
    shutil.copyfile(args.config, cfg_out)
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'testing/configs/hello_world_local.yaml'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 44679) of binary: /home/linuxsys/anaconda3/envs/fluteLatest/bin/python
Traceback (most recent call last):
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/site-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/linuxsys/anaconda3/envs/fluteLatest/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
e2e_trainer.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-10-03_17:01:38
  host      : linuxsys
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 44680)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-10-03_17:01:38
  host      : linuxsys
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 44681)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-10-03_17:01:38
  host      : linuxsys
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 44679)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

Request you to please guide me to solve this isue.

**Comment by Mirian-Hipolito** [comment]
Hi @aviralsangal, thanks for opening this issue. Can you please try changing the **dataPath** and **config** parameters as follows:

`python -m torch.distributed.run --nproc_per_node=3 e2e_trainer.py -dataPath ./testing -outputPath scratch -config testing/hello_world_nlg_gru.yaml -task nlg_gru -backend nccl`

Also make sure the dummy data has been downloaded inside the **testing** folder (Instructions of how to download the data here: https://github.com/microsoft/msrflute/blob/main/testing/README.md)

This should fix the issue. The problem is that FLUTE is not able to find the files pointed in the command line because these have been renamed after our latest commit. We will make sure to update the readme accordingly. Let us know if you present any other issue. 🙂
