### ISSUE TITLE
Sample code CUDA issue

### ISSUE THREAD

**Issue by aviralsangal** [microsoft/msrflute#16]
Hi,
Following is the error, I am getting on running the sample code given in the documentation. Request you to please look into it and help me resolving the issue.

 vision@vision:~/aviral/msrflute$ python -m torch.distributed.run --nproc_per_node=3 e2e_trainer.py -dataPath ./testing -outputPath scratch -config testing/hello_world_nlg_gru.yaml -task nlg_gru -backend nccl
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
The data can be found here:  ./testing
The data can be found here:  ./testing
The data can be found here:  ./testing
Sat Nov 12 14:38:34 2022 : Assigning default values for: {'max_grad_norm', 'batch_size'} in [server_config][val][data_config]
Sat Nov 12 14:38:34 2022 : Assigning default values for: {'max_grad_norm', 'num_frames'} in [server_config][test][data_config]
Sat Nov 12 14:38:34 2022 : Assigning default values for: {'num_frames'} in [client_config][train][data_config]
Sat Nov 12 14:38:34 2022 : Backend: nccl
Sat Nov 12 14:38:34 2022 : Assigning default values for: {'batch_size', 'max_grad_norm'} in [server_config][val][data_config]
Sat Nov 12 14:38:34 2022 : Assigning default values for: {'num_frames', 'max_grad_norm'} in [server_config][test][data_config]
Sat Nov 12 14:38:34 2022 : Assigning default values for: {'num_frames'} in [client_config][train][data_config]
Sat Nov 12 14:38:34 2022 : Backend: nccl
Sat Nov 12 14:38:34 2022 : Assigning default values for: {'batch_size', 'max_grad_norm'} in [server_config][val][data_config]
Sat Nov 12 14:38:34 2022 : Assigning default values for: {'num_frames', 'max_grad_norm'} in [server_config][test][data_config]
Sat Nov 12 14:38:34 2022 : Assigning default values for: {'num_frames'} in [client_config][train][data_config]
Sat Nov 12 14:38:34 2022 : Backend: nccl
Added key: store_based_barrier_key:1 to store for rank: 2
Added key: store_based_barrier_key:1 to store for rank: 0
Added key: store_based_barrier_key:1 to store for rank: 1
Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 3 nodes.
Traceback (most recent call last):
  File "e2e_trainer.py", line 244, in <module>
    run_worker(model_path, config, task, data_path, local_rank, backend)
  File "e2e_trainer.py", line 95, in run_worker
    torch.cuda.set_device(rank)
  File "/home/vision/anaconda3/envs/flute/lib/python3.8/site-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 3 nodes.
Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 3 nodes.
Traceback (most recent call last):
  File "e2e_trainer.py", line 244, in <module>
    run_worker(model_path, config, task, data_path, local_rank, backend)
  File "e2e_trainer.py", line 95, in run_worker
    torch.cuda.set_device(rank)
  File "/home/vision/anaconda3/envs/flute/lib/python3.8/site-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Sat Nov 12 14:38:34 2022 : Assigning worker to GPU 0
Preparing model .. Initializing
GRU(
  (embedding): Embedding()
  (rnn): GRU2(
    (w_ih): Linear(in_features=160, out_features=1536, bias=True)
    (w_hh): Linear(in_features=512, out_features=1536, bias=True)
  )
  (squeeze): Linear(in_features=512, out_features=160, bias=False)
)
Sat Nov 12 14:38:34 2022 : initialize model with default settings
Sat Nov 12 14:38:34 2022 : trying to move the model to GPU
Sat Nov 12 14:38:36 2022 : model: GRU(
  (embedding): Embedding()
  (rnn): GRU2(
    (w_ih): Linear(in_features=160, out_features=1536, bias=True)
    (w_hh): Linear(in_features=512, out_features=1536, bias=True)
  )
  (squeeze): Linear(in_features=512, out_features=160, bias=False)
)
Sat Nov 12 14:38:36 2022 : torch.cuda.memory_allocated(): 10909184
/home/vision/anaconda3/envs/flute/lib/python3.8/site-packages/torch/cuda/memory.py:384: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
Sat Nov 12 14:38:36 2022 : torch.cuda.memory_cached(): 23068672
Sat Nov 12 14:38:36 2022 : torch.cuda.synchronize(): None
Traceback (most recent call last):
  File "e2e_trainer.py", line 244, in <module>
    run_worker(model_path, config, task, data_path, local_rank, backend)
  File "e2e_trainer.py", line 111, in run_worker
    val_dataset = get_dataset(data_path, data_config["val"], task, mode="val", test_only=True)
  File "/home/vision/aviral/msrflute/utils/dataloaders_utils.py", line 94, in get_dataset
    dataset = dataset(data_file, test_only=test_only, user_idx=-1, args=data_config)
  File "experiments/nlg_gru/dataloaders/dataset.py", line 26, in __init__
    self.vocab = load_vocab(kwargs['args']['vocab_dict']) if 'args' in kwargs else load_vocab(vocab_dict)
  File "/home/vision/aviral/msrflute/experiments/nlg_gru/utils/utility.py", line 28, in load_vocab
    with open(url, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './testing/models/vocab_reddit.vocab'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 31988) of binary: /home/vision/anaconda3/envs/flute/bin/python
Traceback (most recent call last):
  File "/home/vision/anaconda3/envs/flute/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vision/anaconda3/envs/flute/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vision/anaconda3/envs/flute/lib/python3.8/site-packages/torch/distributed/run.py", line 728, in <module>
    main()
  File "/home/vision/anaconda3/envs/flute/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/vision/anaconda3/envs/flute/lib/python3.8/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/home/vision/anaconda3/envs/flute/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/vision/anaconda3/envs/flute/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/vision/anaconda3/envs/flute/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
e2e_trainer.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-11-12_14:38:38
  host      : vision
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 31989)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-11-12_14:38:38
  host      : vision
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 31990)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-12_14:38:38
  host      : vision
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 31988)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by Mirian-Hipolito** [comment]
Hi @aviralsangal,

Thanks for opening the issue.  According to the error below, seems like CUDA was not able to find all the 3 GPUs you tried to launch:  

_python -m torch.distributed.run **--nproc_per_node=3** e2e_trainer.py -dataPath ./testing -outputPath scratch -config testing/hello_world_nlg_gru.yaml -task nlg_gru -backend nccl_  

`File "e2e_trainer.py", line 244, in
run_worker(model_path, config, task, data_path, local_rank, backend)
File "e2e_trainer.py", line 95, in run_worker
torch.cuda.set_device(rank)
File "/home/vision/anaconda3/envs/flute/lib/python3.8/site-packages/torch/cuda/init.py", line 313, in set_device
torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Sat Nov 12 14:38:34 2022 : Assigning worker to GPU 0`

However, the first worker was effectively assigned to GPU 0 as you can see in the last line .. Can you please try to run `nvidia-smi`  to check how many available GPUs you have and paste your image here?

Also FLUTE is designed to use at least 2 GPUs when running on NCCL, so in case you only have available 1 GPU I would suggest to try using Gloo backend, let me know if this works! 🙂

Thanks,
Mirian.

**Comment by Mirian-Hipolito** [comment]
Hi @aviralsangal, we are closing this issue given that there is no activity. Please feel free to open it again if the problem persists.

Thanks,
Mirian.

**Comment by Mirian-Hipolito** [comment]
Hi @aviralsangal, we are happy to share that we have removed the restriction of minimum number of GPUs to run FLUTE in our latest release. For more documentation about how to run an experiments using a single GPU, please refer to the [README](README.md).
